pix="""
WITH TIME AS (
	SELECT TIME_ID,SUBSTRING(ACTION_WEEK::varchar(255),5,2) AS WEEK,
	(CASE WHEN action_timestamp::timestamp::time<='15:00:00'::time AND action_timestamp::timestamp::time>='09:00:00'::time THEN 'business_hour'
	ELSE 'non_business_hour' END) IS_BUSINESS_HOUR
	from d_time DT
	JOIN D_WEEK DW
	ON DW.WEEK_ID=DT.WEEK_ID
	ORDER BY ACTION_WEEK
),
ST AS (
	SELECT  A.ACCOUNT_ID,STATE
	FROM ACCOUNTS A 
	JOIN CUSTOMERS C
	ON A.CUSTOMER_ID=C.CUSTOMER_ID
	JOIN CITY CT
	ON C.CUSTOMER_CITY = CT.CITY_ID
	JOIN STATE S
	ON CT.STATE_ID=S.STATE_ID
	)
	
SELECT PIX.ACCOUNT_ID,IN_OR_OUT,PIX_AMOUNT,PIX.STATUS,TIME.IS_BUSINESS_HOUR,WEEK,STATE
FROM PIX_MOVEMENTS PIX
JOIN TIME
ON PIX.PIX_REQUESTED_AT=TIME.TIME_ID 
JOIN ST
ON ST.ACCOUNT_ID=PIX.ACCOUNT_ID
"""
tr="""
WITH TIME AS (
SELECT TIME_ID,
(CASE WHEN action_timestamp::timestamp::time<='15:00:00'::time AND action_timestamp::timestamp::time>='09:00:00'::time THEN 'business_hour'
ELSE 'non_business_hour' END) IS_BUSINESS_HOUR
from d_time
),
T_IN AS (
	SELECT IS_BUSINESS_HOUR,ACCOUNT_ID,AMOUNT,STATUS
	FROM TRANSFER_INS TI
	JOIN TIME
	ON TI.TRANSACTION_REQUESTED_AT=TIME.TIME_ID 
	),
	T_OUT AS (
	SELECT IS_BUSINESS_HOUR,ACCOUNT_ID,AMOUNT,STATUS
	FROM TRANSFER_OUTS TOT
	JOIN TIME
	ON TOT.TRANSACTION_REQUESTED_AT=TIME.TIME_ID 
	)

SELECT *
FROM T_IN
UNION
SELECT * 
FROM T_OUT

"""